name: C/C++ CI

on:
  push:
    branches: [ master, in-dev ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Configure
      run: cmake -DCMAKE_BUILD_TYPE:STRING=Debug .
    - name: Build
      run: make
    - name: Check
      run: make check
