name: "Ubuntu + clang"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CMAKE_BUILD_TYPE: Debug
  CC: clang
  CXX: clang++

jobs:
  ubuntu_2004:
    name: "Ubuntu 20.04: Configure, build and check"
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Configure
      run: CC=${{env.CC}} CXX=${{env.CXX}} cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE:STRING=${{env.CMAKE_BUILD_TYPE}}
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.CMAKE_BUILD_TYPE}}
    - name: Check
      working-directory: ${{github.workspace}}/build
      run: make check
