name: "macOS 26"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CMAKE_BUILD_TYPE: Debug
  JOBS: 2

jobs:
  macos_26:
    name: "MacOS 26: Configure, build and check"
    runs-on: macos-26
    steps:
    - uses: actions/checkout@v6
    - name: Configure
      run: CC=clang CXX=clang++ cmake -B ${{github.workspace}}/build-macos-26 -DCMAKE_BUILD_TYPE:STRING=${{env.CMAKE_BUILD_TYPE}}
    - name: Build
      run: cmake --build ${{github.workspace}}/build-macos-26 --config ${{env.CMAKE_BUILD_TYPE}} -- -j${{env.JOBS}}
    - name: Check
      working-directory: ${{github.workspace}}/build-macos-26
      run: make check
